AssignmentDescription: Описание

PreviousAssignmentShort: Предыдущее
PreviousAssignment: Предыдущее задание
NextAssignmentShort: Следующее
NextAssignment: Следующее задание

AssignmentInfo: Информация
AssignmentDuration: Продолжительность
AssignmentStartDate: Начало
AssignmentEndDate: Конец
AssignmentNotStartedYet: Задание еще не начато.

AssignmentManagePanelTitle: Управление

AssignmentManageUnlockDescription: Открыть задание для студентов. После окончания срока сдачи задание останется разблокированным.
AssignmentManageUnlock: Разблокировать
AssignmentManageLockDescription: Закрыть задание от студентов. Это не приведёт к окончанию срока сдачи.
AssignmentManageLock: Заблокировать

AssignmentManageStopDescription: Установить дату окончания на текущее время. Задание не будет заблокировано.
AssignmentManageStop: Остановить
AssignmentManageStartDescription: Начать проверять и принимать посылки по этому заданию. Задание разблокируется, если необходимо. Если у задания выставлена продолжительность, дата окончания сдачи будет выставлена автоматически.
AssignmentManageStart: Начать

AssignmentManageExtraDayDescription: Отложить срок сдачи дальше на один день.
AssignmentManageExtraDay: Дополнительный день
AssignmentManageSkipDayDescription: Передвинуть срок сдачи ближе на один день. Это может привести к моментальной остановке задания.
AssignmentManageSkipDay: Пропустить день

AssignmentManageResetDescription: Заблокировать задание и очистить сроки.
AssignmentManageReset: Сбросить
