CourseView: Просмотр

Sections: Разделы
Assignments: Задания
Overview: Обзор
Theory: Теоретические материалы

NoSubsections: Нет подразделов.
NoOverview: Нет обзора.
NoTheory: Нет теоретических материалов.

Locked: Закрыто

SectionDuration: Продолжительность
SectionStartDate: Начало
SectionEndDate: Конец
SectionNotStartedYet: Задания в этом разделе еще не начаты.

SectionManagePanelTitle: Управление

SectionManageExtraDayDescription: Отложить срок сдачи дальше на один день для всех заданий.
SectionManageExtraDay: Дополнительный день
SectionManageSkipDayDescription: Передвинуть срок сдачи ближе на один день для всех заданий. Это может привести к моментальной остановке некоторых заданий.
SectionManageSkipDay: Пропустить день

SectionManageUnlockDescription: Открыть все задания в этом разделе для студентов. После окончания срока сдачи задания остаются разблокированными.
SectionManageUnlock: Разблокировать
SectionManageLockDescription: Закрыть все задания в этом разделе от студентов. Это не приведёт к окончанию сроков сдачи.
SectionManageLock: Заблокировать

SectionManageStopDescription: Установить дату окончания всех заданий на текущее время. Задания не будут заблокированы.
SectionManageStop: Остановить
SectionManageStartDescription: Начать проверки и приём посылок по заданиям в этом разделе. Все задания разблокируются. Если у заданий выставлена продолжительность, дата окончания будет выставлена автоматически.
SectionManageStart: Начать

SectionManageResetDescription: Заблокировать все задания и очистить сроки.
SectionManageReset: Сбросить

