StudentGroupsPanelTitle: Группы
RemoveGroupButton: Удалить
NoGroup: Без группы
NoStudentsInGroup: В этой группе пока нет студентов.

Rating: Место в рейтинге
NewStudentName: Имя студента
NewStudentEmail: Адрес эл. почты студента
InviteNewStudent: Пригласить

StudentNamePlaceholder: Введите имя студента
EmailPlaceholder: Адрес эл. почты

GroupNamePlaceholder: Введите название для новой группы
CreateNewGroup: Добавить группу
