SubmissionsNeedAction: Ожидающие проверки
SubmissionsAutomatic: Автоматические
NoSubmissions: Нет посылок.

SubmissionSubmitted: отправлено
SubmissionInvalid: некорректно
SubmissionCompileError: ошибка компиляции
SubmissionTestsFailed: тесты не пройдены
SubmissionTestsPassed: тесты пройдены
SubmissionInReview: на проверке
SubmissionRejected: отказано
SubmissionAccepted: принято
SubmissionErrored: системная ошибка
