WroteAgo ago@Text: написал(а) #{ago}

TimeAgoJustNow: только что
TimeAgoMinutes  n@Int: #{pluralRu n "минуту" "минуты" "минут"} назад
TimeAgoHours    n@Int: #{pluralRu n "час" "часа" "часов"} назад
TimeAgoDays     n@Int: #{pluralRu n "день" "дня" "дней"} назад
TimeAgoWeeks    n@Int: #{pluralRu n "неделю" "недели" "недель"} назад
TimeAgoMonths   n@Int: #{pluralRu n "месяц" "месяца" "месяцев"} назад
TimeAgoYears    n@Int: #{pluralRu n "год" "года" "лет"} назад
