AuthLoginPanelTitle: Пожалуйста, войдите в систему
AuthLoginButton: Войти
AuthNoAccountQuestion: Еще нет аккаунта?

AuthForgotPasswordQuestion: Забыли пароль?
AuthForgotPasswordTitle: Сброс пароля
AuthForgotPasswordPanelTitle: Пожалуйста, введите Ваш адрес эл. почты
AuthForgotPasswordButton: Отправить письмо для сброса пароля

AuthRegisterTitle: Создание аккаунта
AuthRegisterPanelTitle: Создание нового аккаунта
AuthRegisterButton: Создать аккаунт

AuthSetPasswordTitle: Задание пароля
AuthChangePasswordTitle: Смена пароля
AuthSetPasswordPanelTitle: Задание пароля
AuthChangePasswordPanelTitle: Смена пароля

Password: Пароль
ConfirmPassword: Подтвердите пароль
SetPassword: Сохранить пароль

CurrentPassword: Текущий пароль
NewPassword: Новый пароль
ConfirmNewPassword: Потвердите новый пароль
ChangePassword: Сменить пароль
