CourseRepositoryPanelTitle: Репозиторий курса
CourseIdentifier: Идентификатор курса
CourseIdentifierRename: Переименовать
CourseRepositoryURL: URL репозитория курса
UpdateCourseButton: Обновить курс

DangerZonePanelTitle: Опасная зона

TransferOwnership: Передать курс
TransferOwnershipButton: Передать
TransferOwnershipDescription: Передать этот курс во владение другому пользователю.

DeleteCourse: Удалить курс
DeleteCourseButton: Удалить
DeleteCourseDescription: Удалив курс, его невозможно восстановить.
