TeachersPanelTitle: Преподаватели
TeacherRoleDescription: Преподавателям доступны графики курса, а также рейтинг и посылки студентов, и диалоги со студентами.
InviteTeacherButton: Пригласить
InviteTeacherPlaceholder: Введите имя или email преподавателя

AssistantsPanelTitle: Помощники
AssistantRoleDescription: Помощникам доступны только рейтинг и посылки студентов.
InviteAssistantButton: Пригласить
InviteAssistantPlaceholder: Введите имя или email помощника

StaffRemoveButton: Удалить
