AssignmentDescription: Description

PreviousAssignmentShort: Previous
PreviousAssignment: Previous Assignment
NextAssignmentShort: Next
NextAssignment: Next Assignment

AssignmentInfo: Assignment Info
AssignmentDuration: Duration
AssignmentStartDate: Started at
AssignmentEndDate: Ending at
AssignmentNotStartedYet: Not started yet.

AssignmentManagePanelTitle: Manage

AssignmentManageUnlockDescription: Make assignment accessible for students. It will remain unlocked after deadline.
AssignmentManageUnlock: Unlock
AssignmentManageLockDescription: Make assignment inaccessible for students. It will not be counted as deadline.
AssignmentManageLock: Lock

AssignmentManageStopDescription: Make deadline happen now. This will not lock the assignment.
AssignmentManageStop: Stop
AssignmentManageStartDescription: Start check and accept submissions for the assignment. If locked it will be unlocked. If duration present deadline will be set.
AssignmentManageStart: Start

AssignmentManageExtraDayDescription: Move deadline forward by one day.
AssignmentManageExtraDay: Extra day
AssignmentManageSkipDayDescription: Move deadline backward by one day. This may result in immediate deadline.
AssignmentManageSkipDay: Skip day

AssignmentManageResetDescription: Lock assignment and clear deadline.
AssignmentManageReset: Reset

Note: Note!
PleaseUseComputer: Please use laptop or desktop computer to submit solutions!
IfYouReallyWant: If you really want to submit from your phone, you can try.
ShowSubmissionForm: Show submission form.

UploadSolutionButton: Upload solution
UploadSolutionHelpText: Solution should be a single source file.
Solution: Solution
SubmitSolutionButton: Submit solution

NoDeadline: no deadline
