AssignmentDescription: Description

PreviousAssignmentShort: Previous
PreviousAssignment: Previous Assignment
NextAssignmentShort: Next
NextAssignment: Next Assignment

AssignmentInfo: Assignment Info
AssignmentDuration: Duration
AssignmentStartDate: Started at
AssignmentEndDate: Ending at
AssignmentNotStartedYet: Not started yet.

AssignmentManagePanelTitle: Manage

AssignmentManageUnlockDescription: Make assignment accessible for students. It will remain unlocked after deadline.
AssignmentManageUnlock: Unlock
AssignmentManageLockDescription: Make assignment inaccessible for students. It will not be counted as deadline.
AssignmentManageLock: Lock
AssignmentManageStopDescription: Make deadline happen now.
AssignmentManageStop: Stop

AssignmentManageExtraDayDescription: Move deadline forward by one day.
AssignmentManageExtraDay: Extra day
AssignmentManageSkipDayDescription: Move deadline backward by one day. This may result in immediate deadline.
AssignmentManageSkipDay: Skip day
