CourseView: View

Sections: Sections
Assignments: Assignments
Overview: Overview
Theory: Theory & Materials

NoSubsections: No subsections.
NoOverview: No overview.
NoTheory: No theory.

Locked: Locked

SectionDuration: Duration
SectionStartDate: Started at
SectionEndDate: Ending at
SectionNotStartedYet: Section assignments are not started yet.

SectionManagePanelTitle: Manage

SectionManageExtraDayDescription: Move deadline forward by one day for all assignments.
SectionManageExtraDay: Extra day
SectionManageSkipDayDescription: Move deadline backward by one day for all assignments. This may result in immediate deadline for some of them.
SectionManageSkipDay: Skip day

SectionManageUnlockDescription: Make assignments accessible for students. They will remain unlocked after deadline.
SectionManageUnlock: Unlock
SectionManageLockDescription: Make assignments inaccessible for students. It will not be counted as deadline.
SectionManageLock: Lock

SectionManageStopDescription: Make deadline happen now. This will not lock the assignments.
SectionManageStop: Stop
SectionManageStartDescription: Start check and accept submissions for assignments in this section. Locked assignments will be unlocked. If duration present deadline will be set for each assignments.
SectionManageStart: Start

SectionManageResetDescription: Lock all assignments and clear deadlines.
SectionManageReset: Reset
