StudentGroupsPanelTitle: Student Groups
RemoveGroupButton: Remove
NoGroup: No group
NoStudentsInGroup: There are no students in this group yet.

Rating: Rating
NewStudentName: Student name
NewStudentEmail: Student email
InviteNewStudent: Invite student

StudentNamePlaceholder: Type student name
EmailPlaceholder: Email

GroupNamePlaceholder: Type a name for a new group
CreateNewGroup: Create new group
