NotificationsPanelTitle: Notifications

NotificationStudentSubmissionsDescription: When your submission status is updated.
NotificationTeacherSubmissionsDescription: When a submission finished automatic job and asks for a review.

NotificationStudentMessagesDescription: When a teacher sends a message to you.
NotificationTeacherMessagesDescription: When a student sends a message to the system.

NotificationCoursePointsDescription: When you get awarded or fined for a submission or other activity.

NotifyEmail: Email
NotifyWeb: Web

CoursePoints: Course Points

NotificationEmail: Notification Email
PrimaryEmail: Primary email
UpdatePrimaryEmail: Update primary email
