NotificationsPanelTitle: Notifications
NotificationSubmissionsDescription: When your submission status is updated.
NotificationCoursePointsDescription: When you get awarded or fined for a submission or other activity.
NotificationMessagesDescription: When a teacher sends a message to you.

NotifyEmail: Email
NotifyWeb: Web

CoursePoints: Course Points

NotificationEmail: Notification Email
PrimaryEmail: Primary email
UpdatePrimaryEmail: Update primary email
