Assignments: Assignments
Submissions: Submissions
Classmates: Classmates
Messages: Messages
Settings: Settings
SignOut: Sign Out

SiteLanguage lang@Text: Site Language: #{lang}
ChooseYourLanguage: Choose your language
AvailableLanguages: Available Languages

Sections: Sections
Overview: Overview
Theory: Theory & Materials

NoSubsections: No subsections.
NoOverview: No overview.
NoTheory: No theory.

Locked: Locked
