Assignments: Assignments
Submissions: Submissions
Classmates: Classmates
Students: Students
Messages: Messages
Settings: Settings
SignIn: Sign In
SignOut: Sign Out

YouAreNotLoggedIn: You are not logged in

SiteLanguage lang@Text: Site Language: #{lang}
ChooseYourLanguage: Choose your language
AvailableLanguages: Available Languages

Sections: Sections
Overview: Overview
Theory: Theory & Materials

NoSubsections: No subsections.
NoOverview: No overview.
NoTheory: No theory.

Locked: Locked
