Assignments: Задания
Submissions: Посылки
Classmates: Однокурсники
Students: Студенты
Messages: Сообщения
Settings: Настройки
SignIn: Войти
SignOut: Выйти

YouAreNotLoggedIn: Вы не вошли в систему

SiteLanguage lang@Text: Язык сайта: #{lang}
ChooseYourLanguage: Выберите язык
AvailableLanguages: Доступные языки

Locked: Закрыто

AuthLoginPanelTitle: Вход в систему
AuthLoginButton: Войти
AuthNoAccountQuestion: Еще нет аккаунта?

AuthForgotPasswordQuestion: Забыли пароль?
AuthForgotPasswordTitle: Сброс пароля
AuthForgotPasswordPanelTitle: Пожалуйста, введите свой e-mail
AuthForgotPasswordButton: Сбросить пароль

AuthRegisterTitle: Новый пользователь
AuthRegisterPanelTitle: Новый пользователь
AuthRegisterButton: Создать

AuthSetPassowordTitle: Смена пароля
AuthSetPasswordPanelTitle: Смена пароля
AuthSetPasswordButton: Сменить пароль

WroteAgo ago@Text: написал(а) #{ago}

TimeAgoJustNow: только что
TimeAgoMinutes  n@Int: #{pluralRu n "минуту" "минуты" "минут"} назад
TimeAgoHours    n@Int: #{pluralRu n "час" "часа" "часов"} назад
TimeAgoDays     n@Int: #{pluralRu n "день" "дня" "дней"} назад
TimeAgoWeeks    n@Int: #{pluralRu n "неделю" "недели" "недель"} назад
TimeAgoMonths   n@Int: #{pluralRu n "месяц" "месяца" "месяцев"} назад
TimeAgoYears    n@Int: #{pluralRu n "год" "года" "лет"} назад
