Assignments: Задания
Submissions: Посылки
Classmates: Однокурсники
Students: Студенты
Messages: Сообщения
Settings: Настройки
SignIn: Войти
SignOut: Выйти

YouAreNotLoggedIn: Вы не вошли в систему

SiteLanguage lang@Text: Язык сайта: #{lang}
ChooseYourLanguage: Выберите язык
AvailableLanguages: Доступные языки

Locked: Закрыто

AuthLoginPanelTitle: Вход в систему
AuthLoginButton: Войти
AuthNoAccountQuestion: Еще нет аккаунта?

AuthForgotPasswordQuestion: Забыли пароль?
AuthForgotPasswordTitle: Сброс пароля
AuthForgotPasswordPanelTitle: Пожалуйста, введите свой e-mail
AuthForgotPasswordButton: Сбросить пароль

AuthRegisterTitle: Новый пользователь
AuthRegisterPanelTitle: Новый пользователь
AuthRegisterButton: Создать

AuthSetPassowordTitle: Смена пароля
AuthSetPasswordPanelTitle: Смена пароля
AuthSetPasswordButton: Сменить пароль
