CourseRepositoryPanelTitle: Course Repository
CourseIdentifier: Course identifier
CourseIdentifierRename: Rename
CourseRepositoryURL: Course repository URL
UpdateCourseButton: Update course

DangerZonePanelTitle: Danger Zone

TransferOwnership: Transfer ownership
TransferOwnershipButton: Transfer
TransferOwnershipDescription: Transfer this course to another user.

DeleteCourse: Delete course
DeleteCourseButton: Delete
DeleteCourseDescription: Once you delete a course, there is no going back. Please be certain.
