TeachersPanelTitle: Teachers
TeacherRoleDescription: Teachers have access to course graphs as well as student leaderboards, submissions and messages.
InviteTeacherButton: Invite teacher
InviteTeacherPlaceholder: Type teacher name or email

AssistantsPanelTitle: Assistants
AssistantRoleDescription: Assistants have access only to student leaderboards and submissions.
InviteAssistantButton: Invite assistant
InviteAssistantPlaceholder: Type assistant name or email

StaffRemoveButton: Remove
