TeachersPanelTitle: Teachers
TeacherRoleDescription: Teachers have access to course graphs as well as student leaderboards, submissions and messages.
InviteTeacherButton: Invite teacher
InviteTeacherPlaceholder: Type teacher name or email

AssistantsPanelTitle: Assistants
AssistantRoleDescription: Assistants have access only to student leaderboards and submissions.
InviteAssistantButton: Invite assistant
InviteAssistantPlaceholder: Type assistant name or email

NoTeachers: This course has no teachers. Which is strange, cause you should be one.
NoAssistants: This course has no assistants yet.

UnknownTeacher: Unknown teacher
UnknownAssistant: Unknown assistant

StaffRemoveButton: Remove
