NotificationsPanelTitle: Уведомления

NotificationStudentSubmissionsDescription: Когда обновляется статус Вашей посылки.
NotificationTeacherSubmissionsDescription: Когда посылка студента заканчивает автоматическую обработку и требует проверки.

NotificationStudentMessagesDescription: Когда преподаватель отправляет Вам сообщение.
NotificationTeacherMessagesDescription: Когда студент отправляет сообщение системе.

NotificationCoursePointsDescription: Когда Вас награждают или штрафуют за посылку или другие действия.

NotifyEmail: Эл. почта
NotifyWeb: Сайт

CoursePoints: Баллы

NotificationEmail: Эл. почта для уведомлений
PrimaryEmail: Основной адрес эл. почты
UpdatePrimaryEmail: Обновить
