GoldAchievement: Gold Achievement
SilverAchievement: Silver Achievement
BronzeAchievement: Bronze Achievement
SecretAchievement: Secret Achievement

GoldAchievements: Gold Achievements
SilverAchievements: Silver Achievements
BronzeAchievements: Bronze Achievements
SecretAchievements: Secret Achievements

UntitledAchievement: Untitled Achievement
AchievementNoDescription: No description.

AchievementPredefinedHelloWorld: Hello World!
AchievementPredefinedHelloWorldDescription: Submit first solution.

AchievementPredefinedAcceptable: Acceptable
AchievementPredefinedAcceptableDescription: Submit first #accepted solution.
