WroteAgo ago@Text: wrote #{ago}

TimeAgoJustNow: just now
TimeAgoMinutes  n@Int: #{pluralEn n "a minute" "minutes"} ago
TimeAgoHours    n@Int: #{pluralEn n "an hour" "hours"} ago
TimeAgoDays     n@Int: #{pluralEn n "a day" "days"} ago
TimeAgoWeeks    n@Int: #{pluralEn n "a week" "weeks"} ago
TimeAgoMonths   n@Int: #{pluralEn n "a month" "months"} ago
TimeAgoYears    n@Int: #{pluralEn n "a year" "years"} ago
