AuthLoginPanelTitle: Please sign in
AuthLoginButton: Login
AuthNoAccountQuestion: Don't have an account?

AuthForgotPasswordQuestion: Forgot password?
AuthForgotPasswordTitle: Forgot Password
AuthForgotPasswordPanelTitle: Please enter your e-mail address
AuthForgotPasswordButton: Send password reset e-mail

AuthRegisterTitle: New Account
AuthRegisterPanelTitle: Creating a new account
AuthRegisterButton: Register

AuthSetPassowordTitle: Setting Password
AuthSetPasswordPanelTitle: Setting password
Password: Password
ConfirmPassword: Confirm password
SetPassword: Set password
