AuthLoginPanelTitle: Please sign in
AuthLoginButton: Login
AuthNoAccountQuestion: Don't have an account?

AuthForgotPasswordQuestion: Forgot password?
AuthForgotPasswordTitle: Forgot Password
AuthForgotPasswordPanelTitle: Please enter your e-mail address
AuthForgotPasswordButton: Send password reset e-mail

AuthRegisterTitle: New Account
AuthRegisterPanelTitle: Creating a new account
AuthRegisterButton: Register

AuthSetPasswordTitle: Setting Password
AuthChangePasswordTitle: Changing Password
AuthSetPasswordPanelTitle: Setting password
AuthChangePasswordPanelTitle: Change Password

Password: Password
ConfirmPassword: Confirm password
SetPassword: Set password

CurrentPassword: Current password
NewPassword: New password
ConfirmNewPassword: Confirm new password
ChangePassword: Change password
